[package]
name = "instance_builder"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
indicatif = "0.18.3"
log.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
launcher-auth = { path = "../crates/auth" }
shell-words = "1.1.1"
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
winapi.workspace = true
winreg.workspace = true
